### ISSUE TITLE
KeyError for certain locations

### ISSUE THREAD

**Issue by fabaff** [jacobtomlinson/datapoint-python#37]
This example is using Zurich, Switzerland with the coordinates from the Metoffice website.

```bash
$ python3
Python 3.6.6 (default, Jul 19 2018, 14:25:17) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datapoint
>>> conn = datapoint.connection(api_key="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee")
>>> site = conn.get_nearest_site(47.383, 8.567)
>>> forecast = conn.get_forecast_for_site(site.id, "3hourly")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fab/Documents/repos/ha/home-assistant/lib64/python3.6/site-packages/datapoint/Manager.py", line 217, in get_forecast_for_site
    forecast.continent = data['SiteRep']['DV']['Location']['continent']
KeyError: 'Location'
>>> 
```

It works for Paris and London.

Original issue: https://github.com/home-assistant/home-assistant/issues/17492

**Comment by jacobtomlinson** [comment]
This API only provides data for the UK. Putting in locations outside of the UK will result in either misleading data (Paris will be showing the nearest UK location as it is within the UK bounding box) or no data (Zurich is outside of the UK bounding box).

That being said this should be failing more gracefully with an error stating that this location is out of bounds.
